name: active_mri
channels:
  - pytorch
  - anaconda
  - conda-forge
  - defaults
  - inati
dependencies:
  - numpy
  - tensorboardX
  - pytorch
  - torchvision
  - gym
  - h5py
  - matplotlib
  - scikit-image
  - scikit-learn
  - filelock
  - ignite==0.2.0
  - tqdm
  - pytest
  - pytorch-lightning
  - statistics